name: PeraChatGuard
version: 1.1.0
main: me.peranw.chatguard.PeraChatGuardPlugin
api-version: "1.20"
author: PeraNW
commands:
  perachatguard:
    description: PeraChatGuard yönetim komutu
    usage: /perachatguard reload
permissions:
  perachatguard.reload:
    default: op
  perachatguard.bypass:
    default: op
  perachatguard.notify:
    default: op

